linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - gosec
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofumpt
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - stylecheck
    - unconvert
    - unparam
    - whitespace

  disable:
    - gomnd # Magic numbers are sometimes OK
    - wsl   # Whitespace linter is too strict
    - nlreturn # Too strict about newlines
    - exhaustivestruct # Deprecated
    - golint # Deprecated
    - interfacer # Deprecated
    - maligned # Deprecated
    - scopelint # Deprecated

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 10
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  lll:
    line-length: 120
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  nolintlint:
    allow-leading-space: false
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - funlen
    # Exclude some linters from generated files
    - path: generated
      linters:
        - dupl
        - lll
        - funlen
        - gocognit
        - gocyclo
        - goconst
        - godot
        - stylecheck
        - whitespace
        - wsl
        - nlreturn
    # Exclude godox from generated files
    - path: generated
      text: "TODO|FIXME|XXX"
      linters:
        - godox
    # Skip generated files pattern
    - path: "generated.*\\.go"
      linters:
        - dupl
        - lll
        - funlen
        - gocognit
        - gocyclo
        - goconst
        - godot
        - stylecheck

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - third_party
    - testdata
  skip-files:
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"