# See https://pre-commit.com for more information
repos:
  # Go formatting
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-mod-tidy

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Go imports formatting (using local installation)
  - repo: local
    hooks:
      - id: goimports
        name: goimports
        entry: bash -c 'if command -v goimports > /dev/null; then goimports -w "$@"; else echo "goimports not installed"; fi' --
        language: system
        types: [go]
        pass_filenames: true

  # Go vet (using local installation)
  - repo: local
    hooks:
      - id: go-vet
        name: go vet
        entry: bash -c 'go vet ./...'
        language: system
        types: [go]
        pass_filenames: false

  # Optional: golangci-lint (using local installation)
  # Comment this out if you don't want to run it on every commit
  # - repo: local
  #   hooks:
  #     - id: golangci-lint
  #       name: golangci-lint
  #       entry: bash -c 'if command -v golangci-lint > /dev/null; then golangci-lint run --fix; else echo "golangci-lint not installed"; fi'
  #       language: system
  #       types: [go]
  #       pass_filenames: false