// Code generated by Facebook Business API codegen. DO NOT EDIT.

package facebook

import (
	"unified-ads-mcp/internal/facebook/generated/tools"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// GetMCPTools returns all available MCP tools for Facebook Business API
func GetMCPTools(accessToken string) []mcp.Tool {
	return tools.GetAllTools(accessToken)
}

// RegisterMCPTools registers all Facebook Business API tools with the MCP server
func RegisterMCPTools(s *server.MCPServer, accessToken string) error {
	return tools.RegisterTools(s, accessToken)
}
