// Code generated by Facebook Business API codegen. DO NOT EDIT.

// Package facebook provides a client for the Facebook Business API.
package facebook

import (
	"unified-ads-mcp/internal/facebook/generated/tools"
)

// CallTool executes a Facebook Business API tool
func (c *Client) CallTool(name string, args map[string]interface{}) (interface{}, error) {
	return tools.CallTool(c, name, args)
}
